# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Simple Calorie For iPad' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Simple Calorie For iPad
    pod 'AFNetworking', '~> 3.0'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'

end
